#!/usr/bin/env python3
"""Run-plan TSV writer/parser — the ONLY sanctioned way to write plan files.

Schema v2 (FROZEN, PROTOCOL §5 item 10) — 6 TAB-separated fields:

    task | track | subset_manifest | seed | config_yaml | keep_local_traj

* first non-comment row is the literal header above
* '#' comment lines and blank lines are ignored anywhere
* the task id lives IN THE DATA: consumers match column 1 against
  $SLURM_ARRAY_TASK_ID via scripts/plan_reader.awk. Position-based reads
  (physical-line offsets derived from array ids) are FORBIDDEN — a
  regenerated file with a different banner length used to break them
  silently, which forced the Phase-1 pilot-A bypass (PROTOCOL §10).

Hand-editing a committed *.tsv is a protocol violation. Regenerate instead:
    python scripts/gen_run_plan.py                 # rewrite every known plan
    python scripts/gen_run_plan.py --check         # exit 0 iff bytes match

Validation here mirrors scripts/plan_reader.awk; tests keep both honest by
running them against each other.
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parents[1]

COLUMNS = ("task", "track", "subset_manifest", "seed", "config_yaml", "keep_local_traj")
HEADER = "\t".join(COLUMNS)

BANNER = (
    "# SPELL-RQ2 run plan — generated by scripts/gen_run_plan.py. DO NOT hand-edit.",
    "# Schema: task|track|subset_manifest|seed|config_yaml|keep_local_traj",
    "# The reader matches COLUMN-1 == SLURM_ARRAY_TASK_ID (scripts/plan_reader.awk);",
    "# line positions are meaningless by design.",
    "# Sequence discipline (PROTOCOL §7 gate): task 0 (ceiling) runs FIRST and ALONE;",
    "# 'val WER decreasing by epoch ~5' UNLOCKS tasks 1-5 (25% random floors, the",
    "# formal x5 random-floor cell per §3.8 — seeds 101-105, same config).",
)


class PlanError(ValueError):
    """Loud, greppable schema violation (mirrors FATAL[run_plan] awk exits)."""


# --- known plans -------------------------------------------------------------
# Frozen identities preserved verbatim from the pre-schema-v2 file (same
# manifest / seed / config / keep values); only the leading task id is new.
# Tasks 3-5 (2026-08-28) complete the formal x5 random-floor cell (§3.8):
# seeds 103-105, same config as the pilot floors, keep_local_traj=1. The
# yaml filename says x2seeds for historical reasons — the CONFIG is the one
# frozen artifact and is shared by all five floor tasks.
PLANS: dict[str, list[tuple]] = {
    "slurm/run_plan_pilots.tsv": [
        (0, "track_b", "subsets/splits/train_ids.txt", 0,
         "configs/pilot_100pct.yaml", 1),
        (1, "track_b", "subsets/random_25pct_seed101.txt", 101,
         "configs/pilot_25pct_random_x2seeds.yaml", 1),
        (2, "track_b", "subsets/random_25pct_seed102.txt", 102,
         "configs/pilot_25pct_random_x2seeds.yaml", 1),
        (3, "track_b", "subsets/random_25pct_seed103.txt", 103,
         "configs/pilot_25pct_random_x2seeds.yaml", 1),
        (4, "track_b", "subsets/random_25pct_seed104.txt", 104,
         "configs/pilot_25pct_random_x2seeds.yaml", 1),
        (5, "track_b", "subsets/random_25pct_seed105.txt", 105,
         "configs/pilot_25pct_random_x2seeds.yaml", 1),
    ],
}


def validate_rows(rows: list[tuple]) -> None:
    """Raise PlanError on any violation of the frozen schema."""
    seen: set[str] = set()
    for i, row in enumerate(rows):
        if len(row) != len(COLUMNS):
            raise PlanError(f"row {i}: need {len(COLUMNS)} fields, got {len(row)}")
        task, track, manifest, seed, cfg, keep = row
        if not str(task).isdigit():
            raise PlanError(f"row {i}: task id {task!r} is not a non-negative integer")
        if str(task) in seen:
            raise PlanError(f"duplicate task id {task}")
        seen.add(str(task))
        if track not in ("track_a", "track_b"):
            raise PlanError(f"row {i}: unknown track {track!r}")
        if not str(seed).isdigit():
            raise PlanError(f"row {i}: seed {seed!r} is not a non-negative integer")
        if str(keep) not in ("0", "1"):
            raise PlanError(f"row {i}: keep_local_traj {keep!r} must be 0 or 1")
        for label, rel in (("subset_manifest", manifest), ("config_yaml", cfg)):
            p = PROJECT_ROOT / rel
            if not p.is_file():
                raise PlanError(f"row {i}: {label} does not exist under repo root: {rel}")


def render(plan_key: str) -> str:
    """Deterministic file bytes for a known plan (banner + header + sorted rows)."""
    rows = PLANS[plan_key]
    validate_rows(rows)
    lines = [*BANNER, HEADER]
    lines += ["\t".join(str(f) for f in row)
              for row in sorted(rows, key=lambda r: int(r[0]))]
    return "\n".join(lines) + "\n"


def parse_plan(path: str | Path) -> list[tuple]:
    """Parse a plan file into row tuples (python twin of plan_reader.awk).

    Raises PlanError with awk-matching semantics so tests can cross-validate.
    """
    header_seen = False
    rows: list[tuple] = []
    seen: set[str] = set()
    for lineno, raw in enumerate(Path(path).read_text(encoding="utf-8").splitlines(), 1):
        line = raw.strip()
        if not line or line.startswith("#"):
            continue
        fields = tuple(raw.split("\t"))
        if not header_seen:
            if fields != COLUMNS:
                raise PlanError(
                    f"line {lineno}: first non-comment row must be the header "
                    f"'{HEADER}', got '{raw}'")
            if len(fields) != len(COLUMNS):
                raise PlanError(f"line {lineno}: bad header arity")
            header_seen = True
            continue
        if len(fields) != len(COLUMNS):
            raise PlanError(
                f"line {lineno}: need {len(COLUMNS)} tab-separated fields, "
                f"got {len(fields)} ('{raw}')")
        if any(not f for f in fields):
            raise PlanError(f"line {lineno}: empty field ('{raw}')")
        task = fields[0]
        if not task.isdigit():
            raise PlanError(f"line {lineno}: task id '{task}' is not a non-negative integer")
        if task in seen:
            raise PlanError(f"duplicate task id {task} at line {lineno}")
        seen.add(task)
        rows.append(fields)
    if not header_seen:
        raise PlanError("empty plan: only comment/blank lines")
    validate_rows([(f[0], f[1], f[2], f[3], f[4], f[5]) for f in rows])
    return rows


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--check", action="store_true",
                    help="verify every committed plan matches render() byte-for-byte")
    ap.add_argument("--plan", action="append", default=None,
                    help="restrict to one plan key (default: all of PLANS)")
    args = ap.parse_args(argv)

    keys = [args.plan] if args.plan else list(PLANS)
    failures = []
    for key in keys:
        target = PROJECT_ROOT / key
        want = render(key)
        if args.check:
            got = target.read_text(encoding="utf-8") if target.exists() else "<missing>"
            if got != want:
                failures.append(key)
                print(f"[gen_run_plan] MISMATCH {key} — regenerate, never hand-edit",
                      file=sys.stderr)
            else:
                print(f"[gen_run_plan] OK {key}")
        else:
            target.write_text(want, encoding="utf-8")
            print(f"[gen_run_plan] wrote {target}")

    if failures:
        print(f"[gen_run_plan] {len(failures)} plan file(s) diverged from the "
              "sanctioned generator", file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
